name: Add assets to release

on:
  workflow_call:
    inputs:
      upload_url:
        description: "The release upload url"
        required: true
        type: string

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            TARGET: linux
            CMD_BUILD: >
              poetry run pyinstaller --clean -F --hidden-import audible_cli -n audible -c pyi_entrypoint.py &&
              cd dist/ &&
              zip -r9 audible_linux_ubuntu_22_04 audible
            OUT_FILE_NAME: audible_linux_ubuntu_22_04.zip
            ASSET_MIME: application/zip

          - os: ubuntu-20.04
            TARGET: linux
            CMD_BUILD: >
              poetry run pyinstaller --clean -F --hidden-import audible_cli -n audible -c pyi_entrypoint.py &&
              cd dist/ &&
              zip -r9 audible_linux_ubuntu_20_04 audible
            OUT_FILE_NAME: audible_linux_ubuntu_20_04.zip
            ASSET_MIME: application/zip

          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
              poetry run pyinstaller --clean -F --hidden-import audible_cli -n audible -c pyi_entrypoint.py &&
              cd dist/ &&
              zip -r9 audible_mac audible
            OUT_FILE_NAME: audible_mac.zip
            ASSET_MIME: application/zip

          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
              poetry run pyinstaller --clean -D --hidden-import audible_cli -n audible -c pyi_entrypoint.py &&
              cd dist/ &&
              zip -r9 audible_mac_dir audible
            OUT_FILE_NAME: audible_mac_dir.zip
            ASSET_MIME: application/zip

          - os: windows-latest
            TARGET: windows
            CMD_BUILD: >
              poetry run pyinstaller --clean -D --hidden-import audible_cli -n audible -c pyi_entrypoint.py &&
              cd dist/ &&
              powershell Compress-Archive audible audible_win_dir.zip
            OUT_FILE_NAME: audible_win_dir.zip
            ASSET_MIME: application/zip

          - os: windows-latest
            TARGET: windows
            CMD_BUILD: >
              poetry run pyinstaller --clean -F --hidden-import audible_cli -n audible -c pyi_entrypoint.py &&
              cd dist/ &&
              powershell Compress-Archive audible.exe audible_win.zip
            OUT_FILE_NAME: audible_win.zip
            ASSET_MIME: application/zip

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Install dependencies
        run: |
          poetry install --only main
          poetry run pip install --constraint=.github/workflows/constraints.txt pyinstaller
          poetry env list --full-path

      - name: Build with pyinstaller for ${{matrix.TARGET}}
        run: |
          ${{matrix.CMD_BUILD}}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./dist/${{ matrix.OUT_FILE_NAME}}
          asset_name: ${{ matrix.OUT_FILE_NAME }}
          asset_content_type: ${{ matrix.ASSET_MIME }}
