name: "Close stale issues and PRs"

on:
  schedule:
    - cron: "00 03 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          close-issue-message: "This issue has automatically been closed due to no activities."
          close-pr-message: "This pull-request has automatically been closed due to no activities."
          stale-issue-message: "This issue has not been updated for a while and will be closed soon."
          stale-pr-message: "This pull-request has not been updated for a while and will be closed soon."
          days-before-stale: 60
          days-before-close: 10
          exempt-all-milestones: true
          exempt-issue-labels: skip-stale
          exempt-pr-labels: skip-stale
          stale-issue-label: stale
          stale-pr-label: stale
